/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'module11_assignment';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String MINUS = 'assets/minus.png';
  static const String PHOTO = 'assets/photo.png';
  static const String PHOTO2 = 'assets/photo2.png';
  static const String PHOTO3 = 'assets/photo3.png';
  static const String PLUS = 'assets/plus.png';
}
